name: milk

channels:
  - defaults
  - conda-forge
  
dependencies:
  - tqdm=4.64.0
  - pip=22.1.2
  - prettytable=3.3.0
  - python=3.8
  - spyder=5.2.2
  - pandas
  - pydantic
  - seaborn

  # pip packages
  - pip:
    - -e ./