name: milk

channels:
  - defaults
  - conda-forge
  
dependencies:
  #Base MILK
  - tqdm
  - pip=22.1.2
  - prettytable
  - python=3.9
  - pandas
  - pydantic
  - seaborn
  - matplotlib
  - opencv
  - pyqtgraph
  - autopep8
  - numpy
  - ocl_icd_wrapper_apple
  - pyfai
  - pyopencl
  
  # pip packages
  - pip:
    #MILK github installation
    - -e ./
