name: milk

channels:
  - conda-forge
  - defaults

dependencies:
  - pip=22.1.2
  - python=3.8
  - tqdm=4.64.0
  - prettytable=3.3.0

  # pip packages
  - pip:
    - git+https://github.com/lanl/MILK.git@8576c1ca343b12a0e28d60c8bca6e0b21160e80b
